FROM node:13-alpine

MAINTAINER Pampa Nie "nxg@lohosoft.com"

ARG USER_ID
ARG GROUP_ID

# Copy source to container
COPY package.json /usr/app

WORKDIR /usr/app

# install with local servers


# Create a user group 
RUN groupadd $GROUP_ID

# Create a user under group
RUN adduser -S -D -h /usr/app/ $USER_ID $GROUP_ID

# Chown all the files to the app user.
RUN chown -R $USER_ID:$GROUP_ID /usr/app

# Switch to user
USER $USER_ID

# Open the mapped port
#EXPOSE 3000


#ENTRYPOINT [ "python3" ]

#CMD [ "app/app.py" ]

CMD [ "/bin/bash" ]