version: "3"

services:
  server:
    image: node:12
    working_dir: /app
    volumes:
      - ./:/app
      - ./data/certs:/app/certs:ro

    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: sh -c "npm config set registry https://registry.npm.taobao.org && npm install && npm run dev"
